---
title: "Perfecto-Sevilla_Quiz2.rmd"
author: "Covi Perfecto, Luis Carlo Sevilla"
date: "7/29/2021"
output: html_document
---
#### Question 1: 
An article in the Journal of Sound and Vibration ["Measurement of Noise-Evoked Blood Pressure by Means of Averaging Method: Relation between Blood Pressure Rise and PSL" (1991, Vol. 151(3), pp. 383-394)] described a study investigating the relationship between noise exposure and hypertension. The following data are representative of those reported in the article.

```{r, echo= FALSE}
bpr=c(1,0,1,2,5,1,4,6,2,3,5,4,6,8,4,5,7,9,7,6) 
psl=c(60,63,65,70,70,70,80,90,80,80,85,89,90,90,90,90,94,100,100,100)
BPR_PSL= data.frame(bpr,psl)
knitr::kable(BPR_PSL)
```

```{r, echo=TRUE}
library(ggplot2)
scatterBPR_PSL=ggplot(data=BPR_PSL, aes(bpr,psl)) +   
  geom_point()
  
scatterBPR_PSL = scatterBPR_PSL+ geom_point(size=2) +
  xlab("Blood Pressure Rise (mmHg)") +  
  ylab("PSL") +   
  ggtitle("Measurement of Noise-Evoked Blood Pressure") +
  #geom_smooth(method = "lm")
scatterBPR_PSL
```